// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using weHelpTax_.net6_.Model;

#nullable disable

namespace weHelpTax_.net6_.Migrations
{
    [DbContext(typeof(taxPayerApplicationContext))]
    [Migration("20230928064645_adding new model Termwise Tax")]
    partial class addingnewmodelTermwiseTax
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("weHelpTax_.net6_.Model.Department", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Department");
                });

            modelBuilder.Entity("weHelpTax_.net6_.Model.Employee", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<DateTime?>("DateOfBirth")
                        .HasColumnType("datetime2");

                    b.Property<int?>("DepartmentId")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("HireDate")
                        .HasColumnType("datetime2");

                    b.Property<bool?>("IsAlive")
                        .HasColumnType("bit");

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("DepartmentId");

                    b.ToTable("Employee");
                });

            modelBuilder.Entity("weHelpTax_.net6_.Model.Payment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("EmpId")
                        .HasColumnType("int");

                    b.Property<DateTime>("PaymentTime")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("EmpId");

                    b.ToTable("Payment");
                });

            modelBuilder.Entity("weHelpTax_.net6_.Model.Salary", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int?>("EmpId")
                        .HasColumnType("int");

                    b.Property<decimal>("Salary1")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("EmpId");

                    b.ToTable("Salary");
                });

            modelBuilder.Entity("weHelpTax_.net6_.Model.TaxInfo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<double>("SalaryFrom")
                        .HasColumnType("float");

                    b.Property<double>("SalaryTo")
                        .HasColumnType("float");

                    b.Property<double>("TaxRate")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.ToTable("TaxInfo");
                });

            modelBuilder.Entity("weHelpTax_.net6_.Model.Terms", b =>
                {
                    b.Property<int?>("EmpId")
                        .HasColumnType("int");

                    b.Property<bool>("Term1")
                        .HasColumnType("bit");

                    b.Property<bool>("Term2")
                        .HasColumnType("bit");

                    b.Property<bool>("Term3")
                        .HasColumnType("bit");

                    b.HasKey("EmpId");

                    b.ToTable("Terms");
                });

            modelBuilder.Entity("weHelpTax_.net6_.Model.TermSalary", b =>
                {
                    b.Property<int?>("EmpId")
                        .HasColumnType("int");

                    b.Property<decimal>("TaxTerm1")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("TaxTerm2")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("TaxTerm3")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("EmpId");

                    b.ToTable("TermSalary");
                });

            modelBuilder.Entity("weHelpTax_.net6_.Model.Users", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserId"), 1L, 1);

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsAdmin")
                        .HasColumnType("bit");

                    b.Property<string>("Password")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Username")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("weHelpTax_.net6_.Model.Employee", b =>
                {
                    b.HasOne("weHelpTax_.net6_.Model.Department", "Department")
                        .WithMany("Employee")
                        .HasForeignKey("DepartmentId");

                    b.Navigation("Department");
                });

            modelBuilder.Entity("weHelpTax_.net6_.Model.Payment", b =>
                {
                    b.HasOne("weHelpTax_.net6_.Model.Employee", "Emp")
                        .WithMany("Payment")
                        .HasForeignKey("EmpId");

                    b.Navigation("Emp");
                });

            modelBuilder.Entity("weHelpTax_.net6_.Model.Salary", b =>
                {
                    b.HasOne("weHelpTax_.net6_.Model.Employee", "Emp")
                        .WithMany("Salary")
                        .HasForeignKey("EmpId");

                    b.Navigation("Emp");
                });

            modelBuilder.Entity("weHelpTax_.net6_.Model.Department", b =>
                {
                    b.Navigation("Employee");
                });

            modelBuilder.Entity("weHelpTax_.net6_.Model.Employee", b =>
                {
                    b.Navigation("Payment");

                    b.Navigation("Salary");
                });
#pragma warning restore 612, 618
        }
    }
}
